### PR TITLE
[KubernetesManifest] Replacement logic fix

### LINKED ISSUE #11517: KubernetesManifest container substitution regex is not correct in all cases
The image substution supplied in the `containers` input parameter is not done correctly if the deployment file is using the syntax:

```yaml
  spec:
      containers:
      - image: foo/my-image:tag
```

As the regular expression in 
https://github.com/microsoft/azure-pipelines-tasks/blob/7e19e00ddb6f0e7f306bd9bf1dc8732c1d7ba0e1/Tasks/KubernetesManifestV0/src/utils/utilities.ts#L120 is only looking for *spaces* before the keyword `image`.

### PR DESCRIPTION
**Pull request by ds-ms**
Fixes #11517

### CODE REVIEW

File: Tasks/KubernetesManifestV0/src/utils/DeploymentHelper.ts [hunk 1]
```diff
@@ -141,56 +135,28 @@ function annotateResources(files: string[], kubectl: Kubectl, resourceTypes: Res
...
-                    if (KubernetesObjectUtility.isWorkloadEntity(kind)) {
+function updateResourceObjects(filePaths: string[], imagePullSecrets: string[], containers: string[]): string[] {
+    const newObjectsList = [];
+    filePaths.forEach((filePath: string) => {
+        const fileContents = fs.readFileSync(filePath).toString();
+        yaml.safeLoadAll(fileContents, function (inputObject: any) {
+            if (!!inputObject && !!inputObject.kind) {
+                const kind = inputObject.kind;
+                if (KubernetesObjectUtility.isWorkloadEntity(kind)) {
+                    if (!!imagePullSecrets && imagePullSecrets.length > 0) {
```
Comment (vithati) [inline Tasks/KubernetesManifestV0/src/utils/DeploymentHelper.ts]: you can remove !!. if (imagePullSecrets && imagePullSecrets.length > 0) works

File: Tasks/KubernetesManifestV0/src/utils/DeploymentHelper.ts [hunk 2]
```diff
@@ -141,56 +135,28 @@ function annotateResources(files: string[], kubectl: Kubectl, resourceTypes: Res
...
                         KubernetesObjectUtility.updateImagePullSecrets(inputObject, imagePullSecrets, false);
                     }
-                    newObjectsList.push(inputObject);
+                    if (!!containers && containers.length > 0) {
```
Comment (vithati) [inline Tasks/KubernetesManifestV0/src/utils/DeploymentHelper.ts]: you can remove !!

File: Tasks/KubernetesManifestV0/src/utils/KubernetesObjectUtility.ts [hunk 3]
```diff
@@ -287,6 +287,45 @@ function setImagePullSecrets(inputObject: any, newImagePullSecrets: any) {
     return;
 }
 
+export function updateImageDetails(inputObject: any, containers: string[]) {
+    if (!inputObject || !inputObject.spec || !containers) {
+        return;
+    }
+
+    if (!!inputObject.spec.template && !!inputObject.spec.template.spec) {
```
Comment (vithati) [inline Tasks/KubernetesManifestV0/src/utils/KubernetesObjectUtility.ts]: you can remove !! other places

File: Tasks/KubernetesManifestV0/src/utils/KubernetesObjectUtility.ts [hunk 4]
```diff
@@ -287,6 +287,45 @@ function setImagePullSecrets(inputObject: any, newImagePullSecrets: any) {
...
+        if (!!inputObject.spec.template.spec.containers) {
+            updateContainers(inputObject.spec.template.spec.containers, containers);
+        }
+        if (!!inputObject.spec.template.spec.initContainers) {
+            updateContainers(inputObject.spec.template.spec.initContainers, containers);
```
Comment (vithati) [inline Tasks/KubernetesManifestV0/src/utils/KubernetesObjectUtility.ts]: Do we need to update initContainers? init container are different then your deployment containers.

Comment (ds-ms) [reply Tasks/KubernetesManifestV0/src/utils/KubernetesObjectUtility.ts]: If we remove this it could be a breaking change, because it was replacing earlier.

File: Tasks/KubernetesManifestV0/src/utils/KubernetesObjectUtility.ts [hunk 5]
```diff
@@ -287,6 +287,53 @@ function setImagePullSecrets(inputObject: any, newImagePullSecrets: any) {
...
+        if (imageName.indexOf('/') > 0) {
+            const imgParts = imageName.split('/');
+            const registry = imgParts[0];
+            const imgName = imgParts[1].split(':')[0];
+            img = `${registry}/${imgName}`;
+        } else {
+            img = imageName.split(':')[0];
+        }
+        images.forEach(image => {
+            if (image.startsWith(img + ':') || image === img) {
```
Comment (vithati) [inline Tasks/KubernetesManifestV0/src/utils/KubernetesObjectUtility.ts]: if it is same then no need to replace right. image===img we can remove.

File: Tasks/KubernetesManifestV0/src/utils/DeploymentHelper.ts [hunk 6]
```diff
@@ -141,56 +135,28 @@ function annotateResources(files: string[], kubectl: Kubectl, resourceTypes: Res
...
+        const fileContents = fs.readFileSync(filePath).toString();
+        yaml.safeLoadAll(fileContents, function (inputObject: any) {
+            if (inputObject && inputObject.kind) {
+                const kind = inputObject.kind;
+                if (KubernetesObjectUtility.isWorkloadEntity(kind)) {
+                    if (imagePullSecrets && imagePullSecrets.length > 0) {
                         KubernetesObjectUtility.updateImagePullSecrets(inputObject, imagePullSecrets, false);
                     }
-                    newObjectsList.push(inputObject);
+                    if (containers && containers.length > 0) {
```
Comment (vithati) [inline Tasks/KubernetesManifestV0/src/utils/DeploymentHelper.ts]: Add "list" kind handling.

File: Tasks/KubernetesManifestV0/src/utils/KubernetesObjectUtility.ts (hunk 5 above)
Comment (ds-ms) [reply Tasks/KubernetesManifestV0/src/utils/KubernetesObjectUtility.ts]: Good point. The check should be different. I'll fix it
