### PR TITLE
Users/hiyada/global json fixes

### LINKED ISSUE #10922: [DotNetCore Task/Global.json] Invalid version in global.json reveals incorrect error message.
I have given 2.2.x in global,json which shouldn't work and it gave wrong error. Also markup + html tags are not supported in Build logs.

 The version number: 2.2.x doesn't have the correct format. Versions can be given in the following formats`<li>`2.x   => Install latest in major version.`</li><li>`2.2.x => Install latest in major and minor version`</li><li>`2.2.104 => Install exact version`</li><br/>`Find the value of `version` for installing SDK/Runtime, from the releases.json. The link to releases.json of that major.minor version can be found in [**releases-index file.**](https://github.com/dotnet/core/blob/master/release-notes/releases-index.json). Like link to releases.json for 2.2 version is https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/2.2/releases.json

##[error]Version 2.2.x is not allowed. Allowed version types are: majorVersion.x, majorVersion.minorVersion.x, majorVersion.minorVersion.patchVersion

### PR DESCRIPTION
**Pull request by hiyadav**
#10922
#10923
#10920
#10921
#10919

### CODE REVIEW

File: Tasks/UseDotNetV2/models.ts [hunk 1]
```diff
@@ -111,22 +111,20 @@ export class VersionParts {
...
+            ) {
+                throw tl.loc("OnlyExplicitVersionAllowed", version);
             }
             new semver.Range(version);
         }
         catch (ex) {
-            console.log(ex);
-            throw tl.loc("VersionNotAllowed", version)
+            throw tl.loc("VersionNotAllowed", version) + "\nInnerException: " + ex;
         }
```
Comment (sachinma) [inline Tasks/UseDotNetV2/models.ts]: call it more details. And have it in the task.json for localization

File: Tasks/UseDotNetV2/models.ts [hunk 2]
```diff
@@ -155,8 +153,7 @@ export class VersionParts {
             new semver.Range(version);
         }
         catch (ex) {
-            console.log(ex);
-            throw tl.loc("VersionNotAllowed", version)
+            throw tl.loc("VersionNotAllowed", version) + "\nInnerException: " + ex;
```
Comment (sachinma) [inline Tasks/UseDotNetV2/models.ts]: Same as abvoe
