### PR TITLE
Special case ia32

### LINKED ISSUE #9132: Use Node version task fails on x86 agent in x64 machine
os.arch() returns ia32 for the task, because of which the task tries to install 

https://nodejs.org/dist/v6.12.0/node-v6.12.0-win-ia32.7z

URL gives 404

### PR DESCRIPTION
**Pull request by damccorm**
Node uses x86 for these downloads.

Fixes #9132 and #9656

### CODE REVIEW

File: Tasks/NodeToolV0/nodetool.ts [hunk 1]
```diff
@@ -7,6 +7,10 @@ import * as path from 'path';
 let osPlat: string = os.platform();
 let osArch: string = os.arch();
 
+if (osArch.toLowerCase() == 'ia32') {
```
Comment (stephenmichaelf) [inline Tasks/NodeToolV0/nodetool.ts]: Cleaner to move this to function. Also I think generally we use ===.
