### PR TITLE
Fix vstest version parsing to handle non-numeric version strings

### LINKED ISSUE #21998: [REGRESSION]: vstest@3 fails with Visual Studio 18.3.0 installed
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

vstest@3

### Breaking task version

3.272.0

### Last working task version

3.271.0

### Regression Description

The new vstest version parsing fails for vstest version 18.3.0, which seems to return a different format version string.

The test fails to run and render error:

```
Error: Unexpected version number detected for vstest.console.exe
```

The reported version is:

```
VSTest version 18.3.0 (x64)
```

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

_No response_

### Operation system

Windows 11

### Relevant log output

```shell
Error: Unexpected version number detected for vstest.console.exe: VSTest version 18.3.0 (x64)
```

### Full task logs with system.debug enabled

_No response_

### Repro steps

```yml

```

### PR DESCRIPTION
**Pull request by virekumar**
Use regex to extract numeric version (major.minor.patch) from the PowerShell Get-ItemProperty output instead of naive string split. This handles cases where the version string contains non-numeric prefixes or suffixes (e.g. 'VSTest version 18.3.0 (x64)').

Fixes #21998

### **Context**
File version is coming as non int in few old exe. To handle failures adding those as well in scope

---

### **Task Name**
VsTestV3 and VsTestV2

---

### **Description**
Use regex to extract numeric version (major.minor.patch) from the PowerShell Get-ItemProperty output instead of naive string split. This handles cases where the version string contains non-numeric prefixes or suffixes (e.g. 'VSTest version 18.3.0 (x64)').

---

### **Risk Assessment** (Low / Medium / High)  
_Assess the level of risk and provide reasoning (e.g., scope, impact, backward compatibility)._

---

### **Change Behind Feature Flag** (Yes / No)
Not required

---

### **Tech Design / Approach**
Not required

---

### **Documentation Changes Required** (Yes/No)
Not required 

---

### **Unit Tests Added or Updated** (Yes / No)  
Not required

---

### **Additional Testing Performed**
Manual Testing done
Scenario 1 : Getting version from Get-ItemProperty

image

Scenario 2: Getting version from fallback wmic
image
Wmic was not present on my machine, so was not able to test fallback

---

### **Logging Added/Updated** (Yes/No)
Not required

--- 

### **Telemetry Added/Updated** (Yes/No) 
Not required

---

### **Rollback Scenario and Process** (Yes/No)
- Rollback plan is documented. 

---

### **Dependency Impact Assessed and Regression Tested** (Yes/No)
Yes

---

### **Checklist**
- [ ] Related issue linked (if applicable)
- [ ] Task version was bumped — see [versioning guide](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md)
- [ ] Verified the task behaves as expected

### CODE REVIEW

File: Tasks/VsTestV2/versionfinder.ts [hunk 1]
```diff
@@ -33,29 +33,44 @@ export function getVsTestRunnerDetails(testConfig: models.TestConfigurations) {
...
     let output = powershellTool.execSync({ silent: true } as tr.IExecSyncOptions).stdout;
 
+    if (utils.Helper.isNullOrWhitespace(output)) {
+        tl.debug('Primary version query (Get-ItemProperty) returned empty, trying CIM fallback');
+        try {
+            const cimTool = tl.tool('powershell');
+            const cimScript = `
+                & {
+                    param([string]$path)
+                    $escapedPath = $path -replace '\\\\', '\\\\'
```
Comment (vinayakmsft) [inline Tasks/VsTestV2/versionfinder.ts]: why are we using escapedPath?

Comment (virekumar) [reply Tasks/VsTestV2/versionfinder.ts]: Get-CimInstance -Filter uses WQL which requires doubled backslashes (
  C:\\foo\\bar.exe). The -replace '\\', '\\' in PowerShell converts single backslashes to double, same as the old WMIC
  code did in JavaScript.

**Comment by jessehouwing** [comment]
Powershell also has a File version raw property which returns a 4-part pre-parsed version. But I'm not sure what would be the safer.

It looks like MSFT hasn't consistently used a.b.c.d versions everywhere.

**Comment by jessehouwing** [comment]
Does it make sense to first try to parse the File version as a normal 4-part int version? The FileVersionRaw seems ideal for that.

Only if that fails resort to regex? 

And log at least a debug line that a fall ack is attempted?

**Review by vinayakmsft — APPROVED** [review]

**Review by vchandram — APPROVED** [review]
