### PR TITLE
[MavenV2, MavenV3]: Fixed bug when task succeeds on tests failure

### LINKED ISSUE #14514: Maven task succeeds on maven build failure
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven

list here (V# not needed):  https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/MavenV3

## Environment
- Server - Azure Pipelines

    - Account : ailens-io; Project: truera; BuildId=13244 or 20210302.9

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description

Maven task succeeds even though maven build failed. This is likely caused by a bad symlink in the filesystem which makes node_modules/azure-pipelines-task-lib/task.js crash, see below. More in general, seems like pipeline code crash allows task to be marked as successful.
image

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (default-resources) on project rbac: /home/vsts/work/1/s/java/rbac-svc/target/classes/clients.yaml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :rbac
The process '/usr/bin/mvn' failed with exit code 1
Could not retrieve code analysis results - Maven run failed.
(node:2721) UnhandledPromiseRejectionWarning: Error: Failed find: ENOENT: no such file or directory, stat '/home/vsts/work/1/s/java/rbac-svc/target/classes/clients.yaml'
    at find (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/azure-pipelines-task-lib/task.js:819:15)
    at Object.findMatch (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/azure-pipelines-task-lib/task.js:1411:35)
    at publishJUnitTestResults (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/maventask.js:320:39)
    at /home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/maventask.js:263:17
    at _fulfilled (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:854:54)
    at /home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:816:13)
    at /home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:624:44
    at runSingle (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:137:13)
    at flush (/home/vsts/work/_tasks/Maven_ac4ee482-65da-4485-a532-7b085873e532/3.181.1/node_modules/q/q.js:125:13)
(node:2721) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2721) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Finishing: Maven
```

### Task logs

Attached the relevant log above.

Logs from Maven task set up:
```
==============================================================================
Task         : Maven
Description  : Build, test, and deploy with Apache Maven
Version      : 3.181.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/maven
==============================================================================
/usr/bin/mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/apache-maven-3.6.3
Java version: 1.8.0_282, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-1039-azure", arch: "amd64", family: "unix"
FindBugs analysis is enabled.
PMD analysis is enabled.
```

### PR DESCRIPTION
**Pull request by matskan**
**Task name**: MavenV2, MavenV3

**Description**:  Maven task succeeded when tests failed. It was caused by incorrect exception handling on last stage of build. 
Now the build will fail if tests don't finish successfully. 
Added new optional input: `allowBrokenSymlinks`.  If it is set `false` the task will fail when it finds bad symbolic link during publishing tests. For backward-combability it is set `true` by default to ignore incorrect symbolic links when task tries to publish tests.

**Documentation changes required:** Yes
**Added unit tests:** No
**Attached related issue:**  #14514

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected
- [X] There’s no risky dependency updates
- [x] Changes has been tested
- [x] Enough test coverage for changes, and current test coverage for task doesn't look poor
- [X] We understand how tasks is working, how changes affect task behavior
- [ ] There is no breaking changes
- [X] There is no any other concerns
- [x] I have not discovered any new uncovered test/use cases

✔️ [Maven V3 succeeds when tests are passed and there is a bad symlink when task tries to publish tests (`allowBrokenSymlinks = true`)](https://dev.azure.com/v-imatskan/Maven/_build/results?buildId=134&view=results)
:x: [Maven V3 fails when tests are passed (`allowBrokenSymlinks = false`). There is a bad symlink when task tries to publish tests ](https://dev.azure.com/v-imatskan/Maven/_build/results?buildId=138&view=results)
:x: [Maven V3 fails when tests are failed](https://dev.azure.com/v-imatskan/Maven/_build/results?buildId=143&view=results)

✔️ [Maven V2 succeeds when tests are passed and there is a bad symlink when task tries to publish tests (`allowBrokenSymlinks = true`)](https://dev.azure.com/v-imatskan/Maven/_build/results?buildId=139&view=results)
:x: [Maven V2 fails when tests are passed (`allowBrokenSymlinks = false`). There is a bad symlink when task tries to publish tests)](https://dev.azure.com/v-imatskan/Maven/_build/results?buildId=139&view=results)
:x: [Maven V2 fails when tests are failed](https://dev.azure.com/v-imatskan/Maven/_build/results?buildId=144&view=results)

✔️ [On canary app](https://dev.azure.com/v-imatskan/Maven%20Canary/_build/results?buildId=152&view=results)

### CODE REVIEW

**Comment by vladislav-ryzhov** [comment]
Manually tested these changes in this pipeline https://dev.azure.com/v-vryzhov/test/_build?definitionId=2 (#20210326.7, #20210326.6).
Tested MavenV2 and MavenV3 version with a basic java project. Build worked as expected: tests fail and the task fails too.

File: Tasks/MavenV2/maventask.ts [hunk 1]
```diff
@@ -336,9 +341,11 @@ function publishJUnitTestResults(testResultsFiles: string) {
         tl.debug('Pattern found in testResultsFiles parameter');
         var buildFolder = tl.getVariable('System.DefaultWorkingDirectory');
         tl.debug(`buildFolder=${buildFolder}`);
-        matchingJUnitResultFiles = tl.findMatch(buildFolder, testResultsFiles, null, {
-            matchBase: true
-        });
+        matchingJUnitResultFiles = tl.findMatch(buildFolder, testResultsFiles, {
+            allowBrokenSymbolicLinks: true,
```
Comment (anatolybolshakov) [inline Tasks/MavenV2/maventask.ts:345]: Would this be a breaking changes for user who already have some broken symlinks matching passed patterns?

File: Tasks/MavenV2/maventask.ts [hunk 2]
```diff
@@ -286,6 +286,11 @@ async function execBuild() {
             });
 
             // Do not force an exit as publishing results is async and it won't have finished 
+        })
+        .fail(function (err) {
+            // Set task failure if get exception at step 5
+            console.error(err.message);
```
Comment (anatolybolshakov) [inline Tasks/MavenV2/maventask.ts:292]: Could you please describe it more precisely - at this step this error occured?

File: Tasks/MavenV2/maventask.ts (hunk 1 above)
Comment (matskan) [reply Tasks/MavenV2/maventask.ts:345]: If users' test tries to read data from broken symlink, test will be failed and task also will be failed too.

File: Tasks/MavenV2/maventask.ts (hunk 2 above)
Comment (matskan) [reply Tasks/MavenV2/maventask.ts:292]: Updated description, please take a look.

**Review by anatolybolshakov — APPROVED** [review]
LGTM, thanks!

File: Tasks/MavenV2/task.json [hunk 3]
```diff
@@ -103,6 +103,18 @@
...
+            "name": "allowBrokenSymbolicLinks",
+            "aliases": [
+                "allowBrokenSymlinks"
+            ],
+            "type": "boolean",
+            "label": "Allow broken symbolic links",
+            "required": false,
+            "defaultValue": "true",
+            "groupName": "junitTestResults",
+            "helpMarkDown": "Set false to fail build when task finds broken symbolic link during publishing tests result"
```
Comment (DaniilShmelev) [inline Tasks/MavenV2/task.json:116]: I think this option should only be shown when publishing test results is enabled since when it's disabled this option doesn't have any effect on the task

image

```suggestion
            "helpMarkDown": "Set false to fail build when task finds broken symbolic link during publishing tests result",
            "visibleRule": "publishJUnitResults = true"
```

**Review by DaniilShmelev — APPROVED** [review]
Tested these changes manually, everything is working as expected:
✔ [Maven V2 test failures before](https://dev.azure.com/v-dshmelev/playground/_build/results?buildId=986)
✔ [Maven V3 test failures before](https://dev.azure.com/v-dshmelev/playground/_build/results?buildId=987)
❌ [Maven V2 test failures after](https://dev.azure.com/v-dshmelev/playground/_build/results?buildId=988)
❌ [Maven V3 test failures after](https://dev.azure.com/v-dshmelev/playground/_build/results?buildId=989)
❌ [Don't allow broken symlinks](https://dev.azure.com/v-dshmelev/playground/_build/results?buildId=993)
✔ [Allow broken symlinks](https://dev.azure.com/v-dshmelev/playground/_build/results?buildId=994)

Take a look at the suggestion, but other than that LGTM!

File: Tasks/MavenV2/task.json (hunk 3 above)
Comment (matskan) [reply Tasks/MavenV2/task.json:116]: Yes, sure. Thanks a lot.

**Review by anatolybolshakov — APPROVED** [review]
