### PR TITLE
UseDotNetV2: respect rollForward policy in global.json

### LINKED ISSUE #17179: UseDotNetV2 doesn't respect rollForward in global.json
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: UseDotNet

## Environment
- Server - Azure Pipelines
- Agent - Hosted ubuntu-latest

## Issue Description

I'm using the UseDotNetV2 task with "Use Global.json" set to true. My global.json is in the solution directory and the contents are:
```
{
  "sdk": {
    "version": "6.0.403",
    "rollForward": "latestMajor"
  }
}
```
It could be argued that this should install the latest available .NET SDK (`7.0.100` at the moment), instead of `6.0.403`,
as this is the behavior of Visual Studio, and what I think a user would expect.

Another example that works in Visual Studio, but doesn't work with the current task, would be:
```
{
  "sdk": {
    "version": "7.0.0",
    "rollForward": "latestMinor"
  }
}
```
Which should be equivalent to just using the task and specifying version `7.x` but instead of requiring the version to be set in two places (pipeline and `global.json`) it would allow it to be controlled from a single place and always consistent with the developer's environment.

### LINKED ISSUE #19292: [BUG]: `UseDotNet@2` does not download .NET 8 SDK from `global.json`
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

UseDotNet@2

### Task version

2.230.2

### Issue Description

I'm attempting to use `UseDotNet@2` with `ubuntu-latest` to install .NET 8 now it has been released, but I get the following error:
```
##[error]sdk version matching: 8.0.0 could not be found
```

I've checked [releases.json](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/8.0/releases.json) and it has a non-preview build for linux, so it should be finding it, but it fails.

Task in `azure-pipelines.yml`:
```yaml
- task: UseDotNet@2
    inputs:
      packageType: sdk
      useGlobalJson: true
```

`global.json`:
```json
{
  "sdk": {
    "version": "8.0.0",
    "rollForward": "latestFeature"
  }
}
```

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

_No response_

### Operation system

ubuntu-latest

### Relevant log output

```shell
No matching sdk version could be found for specified version: 8.0.0 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
Version 8.0.0 could not be found in its channel, will now search in adjacent channels.
Searching for version in channel 8.0
##[error]sdk version matching: 8.0.0 could not be found
```

### Full task logs with system.debug enabled

<details><pre>
2023-11-17T11:30:14.4316116Z ##[debug]Evaluating condition for step: 'NuGet: SDK'
2023-11-17T11:30:14.4320222Z ##[debug]Evaluating: and(succeeded(), eq(variables['globalJsonExists'], True))
2023-11-17T11:30:14.4320690Z ##[debug]Evaluating and:
2023-11-17T11:30:14.4327246Z ##[debug]..Evaluating succeeded:
2023-11-17T11:30:14.4327771Z ##[debug]..=> True
2023-11-17T11:30:14.4327967Z ##[debug]..Evaluating eq:
2023-11-17T11:30:14.4329207Z ##[debug]....Evaluating indexer:
2023-11-17T11:30:14.4340380Z ##[debug]......Evaluating variables:
2023-11-17T11:30:14.4342867Z ##[debug]......=> Object
2023-11-17T11:30:14.4343511Z ##[debug]......Evaluating String:
2023-11-17T11:30:14.4344021Z ##[debug]......=> 'globalJsonExists'
2023-11-17T11:30:14.4347622Z ##[debug]....=> 'true'
2023-11-17T11:30:14.4348063Z ##[debug]....Evaluating Boolean:
2023-11-17T11:30:14.4348308Z ##[debug]....=> True
2023-11-17T11:30:14.4351188Z ##[debug]....=> 'True'
2023-11-17T11:30:14.4351390Z ##[debug]..=> True
2023-11-17T11:30:14.4351846Z ##[debug]=> True
2023-11-17T11:30:14.4353940Z ##[debug]Expanded: and(True, eq('true', True))
2023-11-17T11:30:14.4354287Z ##[debug]Result: True
2023-11-17T11:30:14.4354566Z ##[section]Starting: NuGet: SDK
2023-11-17T11:30:14.4359489Z ==============================================================================
2023-11-17T11:30:14.4359744Z Task         : Use .NET Core
2023-11-17T11:30:14.4359860Z Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
2023-11-17T11:30:14.4360922Z Version      : 2.230.2
2023-11-17T11:30:14.4361012Z Author       : Microsoft Corporation
2023-11-17T11:30:14.4361160Z Help         : https://aka.ms/AA4xgy0
2023-11-17T11:30:14.4361315Z ==============================================================================
2023-11-17T11:30:14.4881734Z ##[debug]Using node path: /home/vsts/agents/3.230.0/externals/node16/bin/node
2023-11-17T11:30:14.5755386Z ##[debug]agent.TempDirectory=/home/vsts/work/_temp
2023-11-17T11:30:14.5764314Z ##[debug]loading inputs and endpoints
2023-11-17T11:30:14.5768450Z ##[debug]loading INPUT_PACKAGETYPE
2023-11-17T11:30:14.5778024Z ##[debug]loading INPUT_USEGLOBALJSON
2023-11-17T11:30:14.5779597Z ##[debug]loading INPUT_WORKINGDIRECTORY
2023-11-17T11:30:14.5781029Z ##[debug]loading INPUT_INCLUDEPREVIEWVERSIONS
2023-11-17T11:30:14.5782108Z ##[debug]loading INPUT_INSTALLATIONPATH
2023-11-17T11:30:14.5783231Z ##[debug]loading INPUT_PERFORMMULTILEVELLOOKUP
2023-11-17T11:30:14.5784361Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2023-11-17T11:30:14.5789288Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2023-11-17T11:30:14.5790262Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2023-11-17T11:30:14.5792900Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2023-11-17T11:30:14.5795217Z ##[debug]loaded 10
2023-11-17T11:30:14.5799177Z ##[debug]Agent.ProxyUrl=undefined
2023-11-17T11:30:14.5800845Z ##[debug]Agent.CAInfo=undefined
2023-11-17T11:30:14.5801262Z ##[debug]Agent.ClientCert=undefined
2023-11-17T11:30:14.5801970Z ##[debug]Agent.SkipCertValidation=undefined
2023-11-17T11:30:14.6143522Z ##[debug]Agent.ProxyUrl=undefined
2023-11-17T11:30:14.6148612Z ##[debug]Agent.CAInfo=undefined
2023-11-17T11:30:14.6149533Z ##[debug]Agent.ClientCert=undefined
2023-11-17T11:30:14.6150676Z ##[debug]check path : /home/vsts/work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.230.2/node_modules/azure-pipelines-tool-lib/lib.json
2023-11-17T11:30:14.6152384Z ##[debug]adding resource file: /home/vsts/work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.230.2/node_modules/azure-pipelines-tool-lib/lib.json
2023-11-17T11:30:14.6153593Z ##[debug]system.culture=en-US
2023-11-17T11:30:14.6239929Z ##[debug]Setting resource path to /home/vsts/work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.230.2/task.json
2023-11-17T11:30:14.6241618Z ##[debug]check path : /home/vsts/work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.230.2/task.json
2023-11-17T11:30:14.6243268Z ##[debug]adding resource file: /home/vsts/work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.230.2/task.json
2023-11-17T11:30:14.6244284Z ##[debug]system.culture=en-US
2023-11-17T11:30:14.6262180Z ##[debug]check path : /home/vsts/work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.230.2/node_modules/azure-pipelines-tasks-packaging-common/module.json
2023-11-17T11:30:14.6264017Z ##[debug]adding resource file: /home/vsts/work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.230.2/node_modules/azure-pipelines-tasks-packaging-common/module.json
2023-11-17T11:30:14.6266570Z ##[debug]system.culture=en-US
2023-11-17T11:30:14.6274102Z ##[debug]useGlobalJson=true
2023-11-17T11:30:14.6276562Z ##[debug]packageType=sdk
2023-11-17T11:30:14.6276935Z ##[debug]version=undefined
2023-11-17T11:30:14.6277400Z ##[debug]vsVersion=undefined
2023-11-17T11:30:14.6278126Z ##[debug]nugetVersion=undefined
2023-11-17T11:30:14.6279818Z ##[debug]installationPath=/opt/hostedtoolcache/dotnet
2023-11-17T11:30:14.6280559Z ##[debug]performMultiLevelLookup=false
2023-11-17T11:30:14.6281141Z ##[debug]includePreviewVersions=false
2023-11-17T11:30:14.6283309Z ##[debug]workingDirectory=/home/vsts/work/1/s
2023-11-17T11:30:14.6285741Z ##[debug]agent.proxyurl=undefined
2023-11-17T11:30:14.6286317Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_c647e1ac-30dd-42ca-b154-eb81d06f1270_build_126_0
2023-11-17T11:30:14.6292486Z ##[debug]testing directory '/opt/hostedtoolcache/dotnet'
2023-11-17T11:30:14.6293331Z ##[debug]testing directory '/opt/hostedtoolcache'
2023-11-17T11:30:14.6294119Z ##[debug]mkdir '/opt/hostedtoolcache/dotnet'
2023-11-17T11:30:14.6296012Z ##[debug]agent.proxyurl=undefined
2023-11-17T11:30:14.6296633Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_c647e1ac-30dd-42ca-b154-eb81d06f1270_build_126_0
2023-11-17T11:30:14.6300976Z ##[debug]defaultRoot: '/home/vsts/work/1/s'
2023-11-17T11:30:14.6301719Z ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
2023-11-17T11:30:14.6302341Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2023-11-17T11:30:14.6303078Z ##[debug]findOptions.followSymbolicLinks: 'true'
2023-11-17T11:30:14.6303697Z ##[debug]findOptions.skipMissingFiles: 'false'
2023-11-17T11:30:14.6304331Z ##[debug]matchOptions.debug: 'false'
2023-11-17T11:30:14.6305023Z ##[debug]matchOptions.nobrace: 'true'
2023-11-17T11:30:14.6306997Z ##[debug]matchOptions.noglobstar: 'false'
2023-11-17T11:30:14.6307572Z ##[debug]matchOptions.dot: 'true'
2023-11-17T11:30:14.6308128Z ##[debug]matchOptions.noext: 'false'
2023-11-17T11:30:14.6309629Z ##[debug]matchOptions.nocase: 'false'
2023-11-17T11:30:14.6383898Z ##[debug]matchOptions.nonull: 'false'
2023-11-17T11:30:14.6384652Z ##[debug]matchOptions.matchBase: 'false'
2023-11-17T11:30:14.6385819Z ##[debug]matchOptions.nocomment: 'false'
2023-11-17T11:30:14.6386316Z ##[debug]matchOptions.nonegate: 'false'
2023-11-17T11:30:14.6386945Z ##[debug]matchOptions.flipNegate: 'false'
2023-11-17T11:30:14.6387498Z ##[debug]pattern: '**/global.json'
2023-11-17T11:30:14.6387943Z ##[debug]findPath: '/home/vsts/work/1/s'
2023-11-17T11:30:14.6388586Z ##[debug]statOnly: 'false'
2023-11-17T11:30:14.6388948Z ##[debug]findPath: '/home/vsts/work/1/s'
2023-11-17T11:30:14.6389402Z ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
2023-11-17T11:30:14.6389915Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2023-11-17T11:30:14.6390410Z ##[debug]findOptions.followSymbolicLinks: 'true'
2023-11-17T11:30:14.6390895Z ##[debug]findOptions.skipMissingFiles: 'false'
2023-11-17T11:30:14.6391340Z ##[debug]  /home/vsts/work/1/s (directory)
2023-11-17T11:30:14.6391766Z ##[debug]  /home/vsts/work/1/s/.git (directory)
2023-11-17T11:30:14.6392230Z ##[debug]  /home/vsts/work/1/s/.git/FETCH_HEAD (file)
2023-11-17T11:30:14.6392704Z ##[debug]  /home/vsts/work/1/s/.git/HEAD (file)
2023-11-17T11:30:14.6393173Z ##[debug]  /home/vsts/work/1/s/.git/branches (directory)
2023-11-17T11:30:14.6393654Z ##[debug]  /home/vsts/work/1/s/.git/config (file)
2023-11-17T11:30:14.6394268Z ##[debug]  /home/vsts/work/1/s/.git/description (file)
2023-11-17T11:30:14.6394760Z ##[debug]  /home/vsts/work/1/s/.git/hooks (directory)
2023-11-17T11:30:14.6395331Z ##[debug]  /home/vsts/work/1/s/.git/hooks/applypatch-msg.sample (file)
2023-11-17T11:30:14.6395962Z ##[debug]  /home/vsts/work/1/s/.git/hooks/commit-msg.sample (file)
2023-11-17T11:30:14.6396608Z ##[debug]  /home/vsts/work/1/s/.git/hooks/fsmonitor-watchman.sample (file)
2023-11-17T11:30:14.6397252Z ##[debug]  /home/vsts/work/1/s/.git/hooks/post-update.sample (file)
2023-11-17T11:30:14.6397867Z ##[debug]  /home/vsts/work/1/s/.git/hooks/pre-applypatch.sample (file)
2023-11-17T11:30:14.6398479Z ##[debug]  /home/vsts/work/1/s/.git/hooks/pre-commit.sample (file)
2023-11-17T11:30:14.6399164Z ##[debug]  /home/vsts/work/1/s/.git/hooks/pre-merge-commit.sample (file)
2023-11-17T11:30:14.6399779Z ##[debug]  /home/vsts/work/1/s/.git/hooks/pre-push.sample (file)
2023-11-17T11:30:14.6400360Z ##[debug]  /home/vsts/work/1/s/.git/hooks/pre-rebase.sample (file)
2023-11-17T11:30:14.6400956Z ##[debug]  /home/vsts/work/1/s/.git/hooks/pre-receive.sample (file)
2023-11-17T11:30:14.6401583Z ##[debug]  /home/vsts/work/1/s/.git/hooks/prepare-commit-msg.sample (file)
2023-11-17T11:30:14.6402251Z ##[debug]  /home/vsts/work/1/s/.git/hooks/push-to-checkout.sample (file)
2023-11-17T11:30:14.6402903Z ##[debug]  /home/vsts/work/1/s/.git/hooks/sendemail-validate.sample (file)
2023-11-17T11:30:14.6403516Z ##[debug]  /home/vsts/work/1/s/.git/hooks/update.sample (file)
2023-11-17T11:30:14.6404029Z ##[debug]  /home/vsts/work/1/s/.git/index (file)
2023-11-17T11:30:14.6404490Z ##[debug]  /home/vsts/work/1/s/.git/info (directory)
2023-11-17T11:30:14.6404974Z ##[debug]  /home/vsts/work/1/s/.git/info/exclude (file)
2023-11-17T11:30:14.6405466Z ##[debug]  /home/vsts/work/1/s/.git/logs (directory)
2023-11-17T11:30:14.6405943Z ##[debug]  /home/vsts/work/1/s/.git/logs/HEAD (file)
2023-11-17T11:30:14.6406430Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs (directory)
2023-11-17T11:30:14.6406987Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes (directory)
2023-11-17T11:30:14.6407623Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/origin (directory)
2023-11-17T11:30:14.6408305Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/origin/chore (directory)
2023-11-17T11:30:14.6409042Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/origin/chore/dotnet-8 (file)
2023-11-17T11:30:14.6409949Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/origin/chore/remove-context-from-tests (file)
2023-11-17T11:30:14.6410809Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/origin/feature (directory)
2023-11-17T11:30:14.6411615Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/origin/feature/initial-commit (file)
2023-11-17T11:30:14.6412458Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/origin/feature/validators (file)
2023-11-17T11:30:14.6413306Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/origin/feature/validators-3 (file)
2023-11-17T11:30:14.6414067Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/origin/main (file)
2023-11-17T11:30:14.6414723Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/pull (directory)
2023-11-17T11:30:14.6415487Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/pull/6649 (directory)
2023-11-17T11:30:14.6416182Z ##[debug]  /home/vsts/work/1/s/.git/logs/refs/remotes/pull/6649/merge (file)
2023-11-17T11:30:14.6416794Z ##[debug]  /home/vsts/work/1/s/.git/objects (directory)
2023-11-17T11:30:14.6417312Z ##[debug]  /home/vsts/work/1/s/.git/objects/info (directory)
2023-11-17T11:30:14.6417860Z ##[debug]  /home/vsts/work/1/s/.git/objects/pack (directory)
2023-11-17T11:30:14.6418637Z ##[debug]  /home/vsts/work/1/s/.git/objects/pack/pack-3f6ac69aa18d691d622d6d15a9bfb3486b6c1e24.idx (file)
2023-11-17T11:30:14.6419656Z ##[debug]  /home/vsts/work/1/s/.git/objects/pack/pack-3f6ac69aa18d691d622d6d15a9bfb3486b6c1e24.pack (file)
2023-11-17T11:30:14.6420685Z ##[debug]  /home/vsts/work/1/s/.git/objects/pack/pack-3f6ac69aa18d691d622d6d15a9bfb3486b6c1e24.rev (file)
2023-11-17T11:30:14.6421522Z ##[debug]  /home/vsts/work/1/s/.git/refs (directory)
2023-11-17T11:30:14.6422031Z ##[debug]  /home/vsts/work/1/s/.git/refs/heads (directory)
2023-11-17T11:30:14.6422561Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes (directory)
2023-11-17T11:30:14.6423140Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/origin (directory)
2023-11-17T11:30:14.6423786Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/origin/chore (directory)
2023-11-17T11:30:14.6424487Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/origin/chore/dotnet-8 (file)
2023-11-17T11:30:14.6425294Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/origin/chore/remove-context-from-tests (file)
2023-11-17T11:30:14.6426099Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/origin/feature (directory)
2023-11-17T11:30:14.6427047Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/origin/feature/initial-commit (file)
2023-11-17T11:30:14.6427825Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/origin/feature/validators (file)
2023-11-17T11:30:14.6428594Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/origin/feature/validators-3 (file)
2023-11-17T11:30:14.6429299Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/origin/main (file)
2023-11-17T11:30:14.6429902Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/pull (directory)
2023-11-17T11:30:14.6430505Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/pull/6649 (directory)
2023-11-17T11:30:14.6431150Z ##[debug]  /home/vsts/work/1/s/.git/refs/remotes/pull/6649/merge (file)
2023-11-17T11:30:14.6431721Z ##[debug]  /home/vsts/work/1/s/.git/refs/tags (directory)
2023-11-17T11:30:14.6432202Z ##[debug]  /home/vsts/work/1/s/.gitignore (file)
2023-11-17T11:30:14.6432657Z ##[debug]  /home/vsts/work/1/s/.idea (directory)
2023-11-17T11:30:14.6433301Z ##[debug]  /home/vsts/work/1/s/.idea/.idea.Entertainment.Microservices.Validators (directory)
2023-11-17T11:30:14.6434174Z ##[debug]  /home/vsts/work/1/s/.idea/.idea.Entertainment.Microservices.Validators/.idea (directory)
2023-11-17T11:30:14.6435120Z ##[debug]  /home/vsts/work/1/s/.idea/.idea.Entertainment.Microservices.Validators/.idea/.gitignore (file)
2023-11-17T11:30:14.6436076Z ##[debug]  /home/vsts/work/1/s/.idea/.idea.Entertainment.Microservices.Validators/.idea/aws.xml (file)
2023-11-17T11:30:14.6437047Z ##[debug]  /home/vsts/work/1/s/.idea/.idea.Entertainment.Microservices.Validators/.idea/encodings.xml (file)
2023-11-17T11:30:14.6438062Z ##[debug]  /home/vsts/work/1/s/.idea/.idea.Entertainment.Microservices.Validators/.idea/indexLayout.xml (file)
2023-11-17T11:30:14.6438971Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators (directory)
2023-11-17T11:30:14.6439981Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators/Entertainment.Microservices.Validators.csproj (file)
2023-11-17T11:30:14.6441049Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators/ErrorHandling (directory)
2023-11-17T11:30:14.6442094Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators/ErrorHandling/ValidationResultException.cs (file)
2023-11-17T11:30:14.6443113Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators/README.md (file)
2023-11-17T11:30:14.6444082Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators/Validation (directory)
2023-11-17T11:30:14.6445026Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators/Validation/BaseValidator.cs (file)
2023-11-17T11:30:14.6446082Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators/Validation/GeoLocationValidators.cs (file)
2023-11-17T11:30:14.6447115Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators/ValidationDbContext.cs (file)
2023-11-17T11:30:14.6448010Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators.Tests (directory)
2023-11-17T11:30:14.6449097Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators.Tests/Entertainment.Microservices.Validators.Tests.csproj (file)
2023-11-17T11:30:14.6451731Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators.Tests/GeolocationValidatorTests.cs (file)
2023-11-17T11:30:14.6452777Z ##[debug]  /home/vsts/work/1/s/Entertainment.Microservices.Validators.sln (file)
2023-11-17T11:30:14.6453434Z ##[debug]  /home/vsts/work/1/s/azure-pipelines.yml (file)
2023-11-17T11:30:14.6453918Z ##[debug]  /home/vsts/work/1/s/global.json (file)
2023-11-17T11:30:14.6454389Z ##[debug]  /home/vsts/work/1/s/nuget.config (file)
2023-11-17T11:30:14.6454823Z ##[debug]87 results
2023-11-17T11:30:14.6455153Z ##[debug]found 87 paths
2023-11-17T11:30:14.6455488Z ##[debug]applying include pattern
2023-11-17T11:30:14.6455946Z ##[debug]adjustedPattern: '/home/vsts/work/1/s/**/global.json'
2023-11-17T11:30:14.6456423Z ##[debug]1 matches
2023-11-17T11:30:14.6456741Z ##[debug]1 final results
2023-11-17T11:30:15.3019484Z ##[debug]Finding channel 8.0 for version 8.0.0
2023-11-17T11:30:16.8335174Z No matching sdk version could be found for specified version: 8.0.0 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
2023-11-17T11:30:16.8344520Z Version 8.0.0 could not be found in its channel, will now search in adjacent channels.
2023-11-17T11:30:16.8349995Z Searching for version in channel 8.0
2023-11-17T11:30:18.3166130Z ##[debug]task result: Failed
2023-11-17T11:30:18.3197878Z ##[error]sdk version matching: 8.0.0 could not be found
2023-11-17T11:30:18.3205260Z ##[debug]Processed: ##vso[task.issue type=error;]sdk version matching: 8.0.0 could not be found
2023-11-17T11:30:18.3207185Z ##[debug]Processed: ##vso[task.complete result=Failed;]sdk version matching: 8.0.0 could not be found
2023-11-17T11:30:18.3243960Z ##[section]Finishing: NuGet: SDK
</pre></details>

### Repro steps

```yml
pool:
  vm-image: ubuntu-latest

steps:  
  - task: UseDotNet@2
      inputs:
        packageType: sdk
        useGlobalJson: true
```

### LINKED ISSUE #20065: [BUG]: UseDotNet@2 with global.json installs incorrect SDK version
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

UseDotNet

### Task version

2

### Issue Description

I'm using the following task:

```
- task: UseDotNet@2
  displayName: "Install .NET SDK"
    inputs:
      packageType: sdk
      useGlobalJson: true
```

with the following `global.json`

```
{
  "sdk": {
    "version": "8.0.301",
    "rollForward": "latestFeature"
  }
}
```

`latestFeature` should install the latest feature band version, meaning `8.0.xxx`. At the time of writing, this is `8.0.302`.

However, it installs `8.0.301`, which is not desired. I am using `latestFeature` to ensure I always get the latest feature bands and security patches. 

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

_No response_

### Operation system

Windows-Latest

### Relevant log output

```shell
Found version 8.0.301 in channel 8.0 for user specified version spec: 8.0.301
Getting URL to download .NET Core sdk version: 8.0.301.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.238.1\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Version 8.0.301 was not found in cache.
Downloading: https://download.visualstudio.microsoft.com/download/pr/7ac2d880-2d57-4008-850e-4b42b829c354/e1c92cb3b6a85f53cab6fa55b14b49e3/dotnet-sdk-8.0.301-win-x64.zip
Extracting downloaded package D:\a\_temp\7024317f-ea64-4710-afa8-0435e0f177ed.
Extracting archive
C:\Windows\system32\chcp.com 65001
Active code page: 65001

C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\7024317f-ea64-4710-afa8-0435e0f177ed', 'D:\a\_temp\9404')"

Successfully installed .NET Core sdk version 8.0.301.
Creating global tool path and pre-pending to PATH.
Finishing: Install .NET SDK
```

### Full task logs with system.debug enabled

<details>
  <pre>##[debug]adjustedPattern: 'D:\a\1\s\**/global.json'
##[debug]1 matches
##[debug]1 final results
##[debug]Agent environment resources - Disk: D:\ Available 12325.00 MB out of 14333.00 MB, Memory: Used 1972.00 MB out of 7167.00 MB, CPU: Usage 39.92%
##[debug]Finding channel 8.0 for version 8.0.301
Found version 8.0.301 in channel 8.0 for user specified version spec: 8.0.301
##[debug]Processed: ##vso[telemetry.publish area=TaskDeploymentMethod;feature=UseDotNetV2]{"userVersion":"8.0.301", "resolvedVersion":"8.0.301"}
Getting URL to download .NET Core sdk version: 8.0.301.
Detecting OS platform to find correct download package for the OS.
##[debug]which 'powershell'
##[debug]found: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]which 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]found: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command
##[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: & 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.238.1\externals\get-os-platform.ps1'
##[debug]exec tool: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
##[debug]arguments:
##[debug]   -NoLogo
##[debug]   -Sta
##[debug]   -NoProfile
##[debug]   -NonInteractive
##[debug]   -ExecutionPolicy
##[debug]   Unrestricted
##[debug]   -Command
##[debug]   & 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.238.1\externals\get-os-platform.ps1'
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.238.1\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
##[debug]Got download URL for platform with rid: win-x64
##[debug]isExplicit: 8.0.301
##[debug]explicit? true
Version 8.0.301 was not found in cache.
##[debug]
##[debug]Agent.Version=3.241.0
##[debug]Agent.TempDirectory=D:\a\_temp
##[debug]testing directory 'D:\a\_temp'
Downloading: https://download.visualstudio.microsoft.com/download/pr/7ac2d880-2d57-4008-850e-4b42b829c354/e1c92cb3b6a85f53cab6fa55b14b49e3/dotnet-sdk-8.0.301-win-x64.zip
##[debug]destination D:\a\_temp\b2f183bc-a169-4704-b09d-7fef1b4ff772
##[debug]downloading
</pre>
</details>

### Repro steps

```yml
name: $(major).$(minor)$(rev:.r)
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - '**/*.md'

pool:
  vmImage: "windows-latest"

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: Build_Code
        displayName: Build code
        steps:

          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: sdk
              useGlobalJson: true
```

### PR DESCRIPTION
**Pull request by JamieMagee**
### **Context**
Fixes #17179
Fixes #19292
Fixes #20065

When `useGlobalJson` is true, the task only reads `sdk.version` from global.json and ignores `sdk.rollForward`. Users who set `rollForward: latestFeature` (or any other policy) get the exact pinned version installed instead. This means they miss security patches and get different behavior than local dev.

This also fixes the case where users put `"version": "8.0.0"` with `"rollForward": "latestFeature"` and get a "version not found" error (#19292), because `8.0.0` isn't a real SDK version but the rollForward policy would have resolved it to a valid one.

---

### **Task Name**
UseDotNetV2

---

### **Description**
The task now reads `sdk.rollForward` from global.json and widens the version spec before resolving:

- `disable` — exact version, same as current behavior
- `patch` / `latestPatch` — latest patch within the same feature band (e.g. `8.0.100` becomes `>=8.0.100 <8.0.200`)
- `feature` / `latestFeature` — latest feature band in same major.minor (e.g. `8.0.x`)
- `minor` / `latestMinor` — latest minor in same major (e.g. `8.x`)
- `major` / `latestMajor` — latest in same major (e.g. `8.x`, caller handles cross-channel)

Invalid values get a warning and fall back to exact version matching. No new task inputs needed — `rollForward` comes from global.json itself.

No rollForward in global.json = current behavior unchanged.

---

### **Risk Assessment** (Low)
Only affects the `useGlobalJson: true` code path with SDKs. Users without `rollForward` in their global.json see zero change. The widened version spec flows through the same `DotNetCoreVersionFetcher` + `semver.maxSatisfying` pipeline that already handles `x` wildcards.

---

### **Change Behind Feature Flag** (No)
The change is gated on the presence of `sdk.rollForward` in the user's global.json. If the field is absent, nothing changes. That's effectively a user-controlled opt-in.

---

### **Tech Design / Approach**
- `applyRollForwardPolicy(version, rollForward)` in `versionutilities.ts` maps version + policy to a widened spec
- `globaljsonfetcher.ts` reads `sdk.rollForward`, validates it, applies the conversion, then creates a `DotNetCoreVersionFetcher` with `explicitVersioning: false` so the widened spec passes validation
- The `sdk` model class gains an optional `rollForward` field
- Reference: `actions/setup-dotnet` only handles `latestFeature`; this covers all 9 policies

---

### **Documentation Changes Required** (No)
The task's existing `useGlobalJson` input already tells users it reads global.json. The new behavior matches what users already expect based on the .NET SDK docs. No new inputs or changed defaults.

---

### **Unit Tests Added or Updated** (Yes)
6 new tests:
- `applyRollForwardPolicy` — all 9 policies return correct specs
- `applyRollForwardPolicy` — edge cases (unknown policy, prerelease tags, short versions)
- `globaljsonfetcher` — `latestFeature` resolves to `major.minor.x`
- `globaljsonfetcher` — `latestPatch` resolves to feature band range
- `globaljsonfetcher` — invalid policy warns and falls back to exact version

All 55 tests pass (49 existing + 6 new).

---

### **Additional Testing Performed**
Built with `node make.js build --task UseDotNetV2`. Full L0 suite passes. No manual E2E testing yet (draft PR).

---

### **Logging Added/Updated** (Yes)
- `ApplyingRollForwardPolicy` — logs which policy is applied, the original version, and the resolved spec
- `InvalidRollForwardPolicy` — warns when global.json contains an unrecognized rollForward value
- No sensitive data exposed.

---

### **Telemetry Added/Updated** (No)
The existing telemetry in `getVersionInfo` already logs `userVersion` (now the widened spec) and `resolvedVersion`. No new telemetry events needed.

---

### **Rollback Scenario and Process** (Yes)
Revert the commit or pin task version to `2.268.x`. Since the change only activates when `sdk.rollForward` is present in global.json, users can also remove that field as a workaround.

---

### **Dependency Impact Assessed and Regression Tested** (Yes)
No new dependencies. The change uses existing `semver.maxSatisfying` range matching and the existing `DotNetCoreVersionFetcher` pipeline. All 49 pre-existing tests still pass.

---

### **Checklist**
- [x] Related issue linked (if applicable)
- [x] Task version was bumped — see [versioning guide](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md)
- [ ] Verified the task behaves as expected

### CODE REVIEW

File: Tasks/UseDotNetV2/versionutilities.ts [hunk 1]
```diff
@@ -65,10 +65,80 @@ export function getMatchingVersionFromList(versionInfoList: VersionInfo[], versi
...
+
+        case "patch":
+        case "latestPatch": {
+            // Same feature band, latest patch. Feature band = hundreds digit of patch.
+            // e.g. 6.0.403 -> featureBand=4 -> range >=6.0.400 <6.0.500
+            const featureBand = Math.floor(Number.parseInt(patch) / 100) * 100;
+            return `>=${major}.${minor}.${featureBand} <${major}.${minor}.${featureBand + 100}`;
+        }
+
+        case "feature":
```
Comment (tarunramsinghani) [inline Tasks/UseDotNetV2/versionutilities.ts:116]: I believe the behaviour of feature and latestFeature is different i.e. feature minimum version > specified feature version and latest will pick up the latest feature in the band ? Just want to make sure if this was intentional.

Comment (JamieMagee) [reply Tasks/UseDotNetV2/versionutilities.ts:116]: Yes, `feature` is defined as:

> Uses the latest patch level for the specified major, minor, and feature band.
> If not found, rolls forward to the next higher feature band within the same major/minor and uses the latest patch level for that feature band.
> If not found, fails.

and `latestFeature` is defined as:

> Uses the highest installed feature band and patch level that matches the requested major and minor with a feature band and patch level that's greater than or equal to the specified value.
> If not found, fails.

So, while I realise it's not strictly true it (for better or worse) matches the current behaviour of [`actions/setup-dotnet`][1]. And it solves a lot of issues for a lot of users.

I'd prefer to implement feature parity, then fix `UseDotNet@2` and `actions/setup-dotnet` to more strictly match the `global.json` spec.

[1]: https://github.com/actions/setup-dotnet

File: Tasks/UseDotNetV2/globaljsonfetcher.ts [hunk 2]
```diff
@@ -44,7 +72,10 @@ export class globalJsonFetcher {
             var content = this.readGlobalJson(path);
             if (content != null) {
                 tl.loc("GlobalJsonSdkVersion", content.sdk.version, path);
-                return content.sdk.version;
```
Comment (tarunramsinghani) [inline Tasks/UseDotNetV2/globaljsonfetcher.ts:47]: instead of creating new object type, can we jsut return content.sdk or whoel content itself ? was there a reason for a new type ?

Comment (JamieMagee) [reply Tasks/UseDotNetV2/globaljsonfetcher.ts:47]: People put a lot of unnecessary properties in `global.json`. Just look at `dotnet/runtime` for one![^1]

Extracting two properties seems like a minimally good use of TypeScript in general.

[^1]: https://github.com/dotnet/runtime/blob/main/global.json

File: Tasks/UseDotNetV2/task.json [hunk 3]
```diff
@@ -13,8 +13,8 @@
   "author": "Microsoft Corporation",
   "version": {
     "Major": 2,
-    "Minor": 268,
-    "Patch": 2
+    "Minor": 270,
```
Comment (JamieMagee) [inline Tasks/UseDotNetV2/task.json]: Looks like I missed M270 ☹️ 

https://whatsprintis.it

File: Tasks/UseDotNetV2/globaljsonfetcher.ts (hunk 2 above)
Comment (tarunramsinghani) [reply Tasks/UseDotNetV2/globaljsonfetcher.ts:47]: was not aware global.json can have custom properties. looks good to me.

File: Tasks/UseDotNetV2/task.json (hunk 3 above)
Comment (tarunramsinghani) [reply Tasks/UseDotNetV2/task.json]: yes please update to 271.

Comment (JamieMagee) [reply Tasks/UseDotNetV2/task.json]: Done!

**Review by tarunramsinghani — APPROVED** [review]

**Review by sanjuyadav24 — APPROVED** [review]

**Comment by JamieMagee** [comment]
@tarunramsinghani @sanjuyadav24 thanks for the approval. I had to make one additional commit to remove a newline at the end of `task.loc.json`. Could you re-approve please?

**Comment by Frulfump** [comment]
Amazing thank you, but absolutely horrible it took Microsoft many many years to get this done, what are you doing?! Use AI for issues triage and PR review/implementation and get the backlog sorted please.
