### PR TITLE
Source bash tasks instead of executing them

### LINKED ISSUE #7934: Bash V3 task sources script instead of executing it
## Troubleshooting
Troublesome code was found at https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/BashV3/bash.ts#L71

## Environment
- Server - VSTS
- Agent - Private

## Issue Description

When running a Bash V3 task with a target script type of "File Path", the task wraps the target script with something like the following:

```bash
. '/home/vsts/agent01/_work/6/s/ci/build.sh'
```

Sourcing (.) a script instead of executing it is problematic because the source built-in does not set the $0 variable to the target script path.

$0 can be used to make scripts work independently of the current working directory, e.g.:

```bash
main() {
    local project_dir="$(dirname "$0")/.."
    # move to project directory using relative path
    pushd "$project_dir"
        # now run something with a known path
        ./gradlew clean build
        ...
    popd
}

main $*
```

Here's an example of how the wrapper changes $0:
```bash
$ cat target-script.sh:
echo "arg 0: $0, arg 1: $1"

$ cat wrapper.sh
. target-script.sh some-arg

$ sh target-script.sh some-arg
arg 0: target-script.sh, arg 1: some-arg

$ sh wrapper.sh
arg 0: wrapper.sh, arg 1: some-arg
```

Steps to reproduce
1. Place target-script.sh from above in a repository
2. Set up a Bash V3 task, choose "File Path", point it to target-script.sh, and set the arguments to "some-argument"
3. Run the task

Expected outcome:
Log shows something like:
arg 0: /home/vsts/agent01/_work/6/s/**target-script.sh**, arg 1: some-arg

Actual outcome:
Log shows something more akin to:
arg 0: /home/vsts/agent01/_work/_temp/66109fbc-a421-4b3c-a049-3a1f062bd1f9.sh arg 1: some-arg

### PR DESCRIPTION
**Pull request by damccorm**
* Check a variable `AZP_BASHV3_OLD_SOURCE_BEHAVIOR`. If it's `true`, use the old (current) behavior.
* Otherwise, check the executable bit. If set, run the script.
* If not set, throw a warning and use the old behavior. This warning will include a pointer to docs which illustrate the back-compat variable.

Fixes #7934

We did this in #9534 and then had to revert in #11571 because of an error, you can see that I'm not making the same mistake here (I've called out where it was) and I've added testing

### CODE REVIEW

File: Tasks/BashV3/bash.ts [hunk 1]
```diff
@@ -72,7 +73,20 @@ async function run() {
                 targetFilePath = input_filePath;
             }
 
-            contents = `. '${targetFilePath.replace("'", "'\\''")}' ${input_arguments}`.trim();
+            if (old_source_behavior) {
+                contents = `. '${targetFilePath.replace("'", "'\\''")}' ${input_arguments}`.trim();
+            } else {
+                // Check if executable bit is set
+                let stats: fs.Stats = tl.stats(input_filePath);
```
Comment (damccorm) [inline Tasks/BashV3/bash.ts]: This is where the mistake was last time - in the last iteration of this PR, I was doing a stats call on `targetFilePath` instead of `input_filePath`. This is a problem because `targetFilePath` gets some modifications on just windows so that it will work with bash, that cause stats to fail.

**Comment by zachariahcox** [comment]
@stephenmichaelf are you okay with this change?

**Comment by damccorm** [comment]
@stephenmichaelf could you take a look?

File: Tasks/BashV3/bash.ts [hunk 2]
```diff
@@ -45,8 +44,10 @@ async function run() {
         let input_filePath: string;
         let input_arguments: string;
         let input_script: string;
+        let old_source_behavior: boolean;
         let input_targetType: string = tl.getInput('targetType') || '';
         if (input_targetType.toUpperCase() == 'FILEPATH') {
+            old_source_behavior = tl.getBoolInput('AZP_BASHV3_OLD_SOURCE_BEHAVIOR', /*required*/ false);
```
Comment (stephenmichaelf) [inline Tasks/BashV3/bash.ts]: Why are we getting this as an input instead of env var?

File: Tasks/BashV3/bash.ts [hunk 3]
```diff
@@ -72,7 +73,20 @@ async function run() {
                 targetFilePath = input_filePath;
             }
 
-            contents = `. '${targetFilePath.replace("'", "'\\''")}' ${input_arguments}`.trim();
+            if (old_source_behavior) {
```
Comment (stephenmichaelf) [inline Tasks/BashV3/bash.ts]: Instead of saying this is old can we specify as a description of what it was doing along with a note that we plan to remove it later?

File: Tasks/BashV3/bash.ts (hunk 1 above)
Comment (stephenmichaelf) [inline Tasks/BashV3/bash.ts]: Nit: `const`

File: Tasks/BashV3/bash.ts [hunk 4]
```diff
@@ -72,7 +73,20 @@ async function run() {
...
+                contents = `. '${targetFilePath.replace("'", "'\\''")}' ${input_arguments}`.trim();
+            } else {
+                // Check if executable bit is set
+                let stats: fs.Stats = tl.stats(input_filePath);
+                if ((stats.mode & 1) > 0) {
```
Comment (stephenmichaelf) [inline Tasks/BashV3/bash.ts]: Can we add a plain English description of what this is doing :)

File: Tasks/BashV3/bash.ts [hunk 5]
```diff
@@ -72,7 +73,20 @@ async function run() {
...
+                    contents = `bash '${targetFilePath.replace("'", "'\\''")}' ${input_arguments}`.trim();
+                }
+                else {
+                    console.log(stats.mode);
```
Comment (stephenmichaelf) [inline Tasks/BashV3/bash.ts]: Do we want this to be a debug log and have some description of what it's printing?

File: Tasks/BashV3/bash.ts (hunk 3 above)
Comment (damccorm) [reply Tasks/BashV3/bash.ts]: Added explanatory comment.

File: Tasks/BashV3/bash.ts (hunk 4 above)
Comment (damccorm) [reply Tasks/BashV3/bash.ts]: Sure, done

File: Tasks/BashV3/bash.ts (hunk 5 above)
Comment (damccorm) [reply Tasks/BashV3/bash.ts]: Good catch.

File: Tasks/BashV3/bash.ts (hunk 2 above)
Comment (damccorm) [reply Tasks/BashV3/bash.ts]: ¯\_(ツ)_/¯ - updated to use env.

File: Tasks/BashV3/bash.ts (hunk 3 above)
Comment (damccorm) [reply Tasks/BashV3/bash.ts]: We don't have a plan to remove this though
